from __future__ import annotations

from enum import StrEnum


class JobStatus(StrEnum):
    UPLOADED = "UPLOADED"
    QUEUED = "QUEUED"
    LOCKED = "LOCKED"
    VALIDATING_IMAGE = "VALIDATING_IMAGE"
    PROCESSING_BACKGROUND = "PROCESSING_BACKGROUND"
    LOADING_MODEL = "LOADING_MODEL"
    GENERATING_MESH = "GENERATING_MESH"
    BAKING_TEXTURE = "BAKING_TEXTURE"
    CONVERTING_GLB = "CONVERTING_GLB"
    OPTIMISING_MODEL = "OPTIMISING_MODEL"
    GENERATING_THUMBNAIL = "GENERATING_THUMBNAIL"
    UPLOADING_RESULTS = "UPLOADING_RESULTS"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED_DEMO = "APPROVED_DEMO"
    REJECTED = "REJECTED"
    AWAITING_PACKAGE = "AWAITING_PACKAGE"
    AWAITING_PAYMENT = "AWAITING_PAYMENT"
    PRODUCTION_APPROVED = "PRODUCTION_APPROVED"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


PROGRESS: dict[JobStatus, int] = {
    JobStatus.UPLOADED: 0,
    JobStatus.QUEUED: 2,
    JobStatus.LOCKED: 4,
    JobStatus.VALIDATING_IMAGE: 8,
    JobStatus.PROCESSING_BACKGROUND: 15,
    JobStatus.LOADING_MODEL: 22,
    JobStatus.GENERATING_MESH: 40,
    JobStatus.BAKING_TEXTURE: 58,
    JobStatus.CONVERTING_GLB: 68,
    JobStatus.OPTIMISING_MODEL: 76,
    JobStatus.GENERATING_THUMBNAIL: 86,
    JobStatus.UPLOADING_RESULTS: 94,
    JobStatus.READY_FOR_REVIEW: 100,
    JobStatus.NEEDS_MANUAL_REVIEW: 100,
    JobStatus.CHANGES_REQUESTED: 100,
    JobStatus.APPROVED_DEMO: 100,
    JobStatus.REJECTED: 100,
    JobStatus.AWAITING_PACKAGE: 100,
    JobStatus.AWAITING_PAYMENT: 100,
    JobStatus.PRODUCTION_APPROVED: 100,
    JobStatus.PUBLISHED: 100,
    JobStatus.FAILED: 100,
    JobStatus.CANCELLED: 100,
}

PROCESSING_STATUSES = {
    JobStatus.LOCKED,
    JobStatus.VALIDATING_IMAGE,
    JobStatus.PROCESSING_BACKGROUND,
    JobStatus.LOADING_MODEL,
    JobStatus.GENERATING_MESH,
    JobStatus.BAKING_TEXTURE,
    JobStatus.CONVERTING_GLB,
    JobStatus.OPTIMISING_MODEL,
    JobStatus.GENERATING_THUMBNAIL,
    JobStatus.UPLOADING_RESULTS,
}

TERMINAL_STATUSES = {JobStatus.PUBLISHED, JobStatus.FAILED, JobStatus.CANCELLED, JobStatus.REJECTED}
