"use client";

import { useState } from "react";
import { LoaderCircle, LockKeyhole, RefreshCw, ShieldCheck, UserPlus, UsersRound } from "lucide-react";
import { Badge, Button, Card } from "@bsocio/ui";
import { apiPost, useApi } from "@/hooks/use-api";
import { PageHeader } from "@/components/dashboard-pages";

interface Customer { _id: string; fullName: string; email: string; country: string; countryCallingCode: string; mobileNumber: string; emailVerifiedAt?: string; suspendedAt?: string; suspensionReason?: string; createdAt: string }
interface TeamMember { _id: string; fullName: string; email: string; role: string; suspendedAt?: string; createdAt: string }

const human = (value: string) => value.toLowerCase().replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase());

export function CustomerAccounts() {
  const state = useApi<{ items: Customer[] }>("/api/admin/records/customers"); const [reasons, setReasons] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  async function change(customer: Customer, action: "SUSPEND" | "RESTORE") { setBusy(customer._id); setMessage(""); try { await apiPost("/api/admin/customers/account", { userId: customer._id, action, reason: action === "SUSPEND" ? reasons[customer._id] : undefined }); setMessage(action === "SUSPEND" ? "Customer suspended and active sessions revoked." : "Customer and business restored."); await state.reload(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Account action failed."); } finally { setBusy(""); } }
  return <div className="dashboard-page"><PageHeader title="Customers" description="Ownership context, verification state and audited account suspension." />{message ? <div className="form-alert" role="status">{message}</div> : null}{state.loading ? <Card className="skeleton-card large" /> : state.error || !state.data ? <Card className="error-state"><strong>{state.error}</strong><Button variant="secondary" onClick={state.reload}><RefreshCw size={17} /> Retry</Button></Card> : state.data.items.length === 0 ? <Card className="empty-state"><UsersRound size={38} /><strong>No customer accounts yet</strong></Card> : <div className="review-grid">{state.data.items.map((customer) => <Card className="review-card" key={customer._id}><div className="record-title"><div><strong>{customer.fullName}</strong><small>{customer.email} · {customer.countryCallingCode} {customer.mobileNumber}</small></div><Badge tone={customer.suspendedAt ? "danger" : "success"}>{customer.suspendedAt ? "Suspended" : "Active"}</Badge></div><p>{customer.country} · email {customer.emailVerifiedAt ? "verified" : "unverified"} · joined {new Date(customer.createdAt).toLocaleDateString()}</p>{customer.suspendedAt ? <><p className="form-alert">Reason: {customer.suspensionReason || "Not recorded"}</p><Button onClick={() => change(customer, "RESTORE")} disabled={Boolean(busy)}><ShieldCheck size={17} /> Restore account</Button></> : <><label className="field"><span className="field-label">Required suspension reason</span><textarea className="input" value={reasons[customer._id] ?? ""} onChange={(event) => setReasons((current) => ({ ...current, [customer._id]: event.target.value }))} maxLength={1000} /></label><Button variant="danger" onClick={() => change(customer, "SUSPEND")} disabled={Boolean(busy) || (reasons[customer._id]?.trim().length ?? 0) < 3}>{busy === customer._id ? <LoaderCircle className="spin" size={17} /> : <LockKeyhole size={17} />} Suspend and revoke sessions</Button></>}</Card>)}</div>}</div>;
}

export function TeamMembers() {
  const state = useApi<{ items: TeamMember[] }>("/api/admin/records/team-members"); const session = useApi<{ user: { role: string } }>("/api/auth/session"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [form, setForm] = useState({ fullName: "", email: "", role: "DEMO_REVIEWER", password: "" });
  function update(name: keyof typeof form, value: string) { setForm((current) => ({ ...current, [name]: value })); }
  async function create() { setBusy(true); setMessage(""); try { await apiPost("/api/admin/team-members", form); setMessage("Team member created with the selected least-privilege role."); setForm({ fullName: "", email: "", role: "DEMO_REVIEWER", password: "" }); await state.reload(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Team member creation failed."); } finally { setBusy(false); } }
  return <div className="dashboard-page"><PageHeader title="Team members" description="Provision administrator accounts without any public administrator registration." />{message ? <div className="form-alert" role="status">{message}</div> : null}{session.data?.user.role === "SUPER_ADMIN" ? <Card className="content-card"><div className="content-card-head"><div><h2>Create team member</h2><p className="muted">Super administrators can assign only operational roles; additional super administrators remain environment-controlled.</p></div><UserPlus size={22} /></div><div className="form-grid"><label className="field"><span className="field-label">Full name</span><input className="input" value={form.fullName} onChange={(event) => update("fullName", event.target.value)} /></label><label className="field"><span className="field-label">Email</span><input className="input" type="email" value={form.email} onChange={(event) => update("email", event.target.value)} /></label><label className="field"><span className="field-label">Role</span><select className="input" value={form.role} onChange={(event) => update("role", event.target.value)}>{["ADMIN", "DEMO_REVIEWER", "THREE_D_REVIEWER", "AR_PUBLISHER", "SALES_MANAGER", "FINANCE_MANAGER", "SUPPORT_MANAGER"].map((role) => <option value={role} key={role}>{human(role)}</option>)}</select></label><label className="field"><span className="field-label">Temporary password</span><input className="input" type="password" autoComplete="new-password" value={form.password} onChange={(event) => update("password", event.target.value)} /><small className="field-hint">At least 12 characters with upper/lowercase, number and symbol.</small></label></div><Button onClick={create} disabled={busy || !form.fullName || !form.email || form.password.length < 12}>{busy ? <LoaderCircle className="spin" size={17} /> : <UserPlus size={17} />} Create team member</Button></Card> : null}{state.loading ? <Card className="skeleton-card large" /> : state.error || !state.data ? <Card className="error-state"><strong>{state.error}</strong><Button variant="secondary" onClick={state.reload}><RefreshCw size={17} /> Retry</Button></Card> : <div className="review-grid">{state.data.items.map((member) => <Card className="content-card" key={member._id}><div className="record-title"><div><strong>{member.fullName}</strong><small>{member.email}</small></div><Badge tone={member.suspendedAt ? "danger" : "info"}>{member.suspendedAt ? "Suspended" : human(member.role)}</Badge></div><p>Created {new Date(member.createdAt).toLocaleDateString()}</p></Card>)}</div>}</div>;
}
