"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { AlertTriangle, Box, CheckCircle2, FileImage, LoaderCircle, UploadCloud } from "lucide-react";
import { Badge, Button, Card, Progress } from "@bsocio/ui";
import { apiPost, useApi } from "@/hooks/use-api";
import { PageHeader } from "@/components/dashboard-pages";
import { SecureModelViewer } from "@/components/secure-model-viewer";

interface ProductDetail {
  product: { _id: string; name: string; category: string; description: string; approvalStatus: string; material: string; colour: string; mainImageAssetId?: string; dimensions: { width: number; height: number; depth: number; unit: string } };
  assets: Array<{ _id: string; assetType: string; originalName: string; status: string; metadata?: { slot?: string } }>;
  jobs: Array<{ _id: string; status: string; progress: number; currentStep: string; customerSafeError?: string }>;
  models: Array<{ _id: string; version: number; status: string; fileSize?: number; validationWarnings?: string[] }>;
  ar?: { status: string; draftSlug: string } | null;
  qr?: { uniqueCode: string; active: boolean } | null;
  approvals: Array<{ _id: string; decision: string; customerFeedback?: string; createdAt: string }>;
}

const human = (value: string) => value.toLowerCase().replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase());
export function ProductWorkspace({ productId }: { productId: string }) {
  const { data, error, loading, reload } = useApi<ProductDetail>(`/api/products/${productId}`);
  if (loading) return <div className="dashboard-page"><PageHeader title="Product" description="Loading secure product workspace…" /><Card className="skeleton-card large" /></div>;
  if (error || !data) return <div className="dashboard-page"><PageHeader title="Product unavailable" description="We could not open this product." /><Card className="error-state"><AlertTriangle /><span>{error}</span><Link className="button button-secondary" href="/dashboard/products">Back to products</Link></Card></div>;
  const product = data.product; const currentJob = data.jobs[0]; const latestModel = data.models[0];
  return <div className="dashboard-page"><PageHeader title={product.name} description={`${product.category} · ${product.material} · ${product.colour}`} action={<Badge tone={product.approvalStatus === "PUBLISHED" || product.approvalStatus === "APPROVED_DEMO" ? "success" : product.approvalStatus === "CHANGES_REQUESTED" ? "warning" : "info"}>{human(product.approvalStatus)}</Badge>} />
    <div className="product-layout"><div className="product-primary"><Card className="content-card"><div className="content-card-head"><div><h2>Product details</h2><p className="muted">{product.description}</p></div></div><dl className="detail-grid"><div><dt>Dimensions</dt><dd>{product.dimensions.width} × {product.dimensions.height} × {product.dimensions.depth} {product.dimensions.unit}</dd></div><div><dt>Private assets</dt><dd>{data.assets.length}</dd></div><div><dt>Model versions</dt><dd>{data.models.length}</dd></div><div><dt>AR status</dt><dd>{data.ar ? human(data.ar.status) : "Not created"}</dd></div></dl></Card>{product.approvalStatus === "CHANGES_REQUESTED" ? <RevisionRequest productId={productId} approval={data.approvals[0]} reload={reload} /> : null}
    <Card className="content-card"><div className="content-card-head"><div><h2>Private image uploads</h2><p className="muted">JPG, PNG or WebP, up to 15 MB. Originals never become public.</p></div></div><UploadPanel productId={productId} initialSourceAssetId={product.mainImageAssetId} onComplete={reload} />{data.assets.length ? <div className="asset-list">{data.assets.map((asset) => <div key={asset._id}><FileImage size={18} /><span><strong>{String(asset.metadata?.slot ?? asset.assetType)}</strong><small>{asset.originalName}</small></span><Badge tone={asset.status === "VALIDATED" ? "success" : "neutral"}>{human(asset.status)}</Badge></div>)}</div> : null}</Card>
    {currentJob ? <Card className="content-card"><div className="content-card-head"><div><h2>3D generation</h2><p className="muted">Accurate progress from the self-hosted worker.</p></div><Badge tone={currentJob.status === "FAILED" ? "danger" : currentJob.status === "READY_FOR_REVIEW" ? "success" : "info"}>{human(currentJob.status)}</Badge></div><Progress value={currentJob.progress} label={currentJob.currentStep} />{currentJob.customerSafeError ? <p className="form-alert">{currentJob.customerSafeError}</p> : null}</Card> : null}
    {latestModel ? <Card className="content-card"><div className="content-card-head"><div><h2>Model preview</h2><p className="muted">Version {latestModel.version}{latestModel.fileSize ? ` · ${(latestModel.fileSize / 1_048_576).toFixed(1)} MB` : ""}</p></div><Badge tone="success">{human(latestModel.status)}</Badge></div><SecureModelViewer modelId={latestModel._id} productName={product.name} />{latestModel.validationWarnings?.length ? <ul className="warning-list">{latestModel.validationWarnings.map((warning) => <li key={warning}>{warning}</li>)}</ul> : null}</Card> : null}</div>
    <aside className="product-side"><Card className="content-card"><h3>Experience outputs</h3><div className="output-list"><div><ScanIcon done={Boolean(data.ar)} /><span><strong>AR experience</strong><small>{data.ar ? human(data.ar.status) : "Created after model review"}</small></span></div><div><ScanIcon done={Boolean(data.qr)} /><span><strong>Dynamic QR</strong><small>{data.qr ? (data.qr.active ? "Live" : "Draft and private") : "Created automatically"}</small></span></div></div>{data.qr ? <Image className="qr-preview" src={`/api/qr/${data.qr.uniqueCode}/svg`} alt={`Dynamic QR preview for ${product.name}`} width={420} height={420} unoptimized /> : null}</Card></aside></div>
  </div>;
}

function RevisionRequest({ productId, approval, reload }: { productId: string; approval?: ProductDetail["approvals"][number]; reload: () => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function resubmit() { setBusy(true); setMessage(""); try { await apiPost("/api/products/resubmit", { productId }); setMessage("Revised product returned to administrator review."); await reload(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Resubmission failed."); } finally { setBusy(false); } }
  const regeneration = approval?.decision === "REQUEST_REGENERATION";
  return <Card className="content-card revision-card"><div className="content-card-head"><div><h2>Administrator requested changes</h2><p className="muted">{approval?.customerFeedback || "Review the request, update the private product evidence and resubmit."}</p></div><Badge tone="warning">{approval ? human(approval.decision) : "Changes requested"}</Badge></div><p>{regeneration ? "Upload the correct main image and use Create 3D job to safely requeue this product without consuming another demo job slot." : "Upload the requested new image, then return the product to review."}</p>{!regeneration ? <Button onClick={resubmit} disabled={busy}>{busy ? <LoaderCircle className="spin" size={17} /> : <CheckCircle2 size={17} />} Resubmit revised product</Button> : null}{message ? <div className="form-alert" role="status">{message}</div> : null}</Card>;
}

function ScanIcon({ done }: { done: boolean }) { return done ? <CheckCircle2 size={20} className="success-icon" /> : <Box size={20} className="muted-icon" />; }

function UploadPanel({ productId, initialSourceAssetId, onComplete }: { productId: string; initialSourceAssetId?: string; onComplete: () => Promise<void> }) {
  const [file, setFile] = useState<File | null>(null); const [slot, setSlot] = useState("MAIN"); const [progress, setProgress] = useState(0); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [sourceAssetId, setSourceAssetId] = useState(initialSourceAssetId ?? ""); const inputRef = useRef<HTMLInputElement>(null);
  async function checksum(selected: File) { const digest = await crypto.subtle.digest("SHA-256", await selected.arrayBuffer()); return Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
  function put(url: string, selected: File, headers: Record<string, string>) { return new Promise<void>((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open("PUT", url); Object.entries(headers).forEach(([key, value]) => xhr.setRequestHeader(key, value)); xhr.upload.onprogress = (event) => { if (event.lengthComputable) setProgress(Math.round((event.loaded / event.total) * 100)); }; xhr.onerror = () => reject(new Error("The direct R2 upload was interrupted. Your product data is still saved.")); xhr.onload = () => xhr.status >= 200 && xhr.status < 300 ? resolve() : reject(new Error(`Private upload failed with status ${xhr.status}.`)); xhr.send(selected); }); }
  async function upload() { if (!file) return; setBusy(true); setError(""); setMessage(""); setProgress(1); try { const sha = await checksum(file); const signed = await apiPost<{ assetId: string; url: string; requiredHeaders: Record<string, string> }>("/api/uploads/sign", { productId, assetType: slot === "SUPPORTING" ? "SUPPORTING_IMAGE" : "ORIGINAL_IMAGE", slot, originalName: file.name, mimeType: file.type, size: file.size, checksumSha256: sha }); await put(signed.url, file, signed.requiredHeaders); await apiPost("/api/uploads/confirm", { assetId: signed.assetId, checksumSha256: sha }); if (slot === "MAIN") setSourceAssetId(signed.assetId); setMessage("Private upload validated successfully."); setFile(null); if (inputRef.current) inputRef.current.value = ""; await onComplete(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Upload failed."); } finally { setBusy(false); } }
  async function createJob() { setBusy(true); setError(""); try { await apiPost("/api/jobs", { productId, sourceAssetId }); setMessage("3D job queued. It will wait safely when the worker is offline."); await onComplete(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not create the 3D job."); } finally { setBusy(false); } }
  return <div className="upload-panel"><div className="upload-controls"><label className="field"><span className="field-label">Image position</span><select className="input" value={slot} onChange={(event) => setSlot(event.target.value)}><option value="MAIN">Main image</option><option value="FRONT">Front</option><option value="BACK">Back</option><option value="LEFT">Left</option><option value="RIGHT">Right</option><option value="TOP">Top</option><option value="SUPPORTING">Supporting image</option></select></label><label className="file-drop"><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><UploadCloud size={24} /><span>{file ? file.name : "Choose a product image"}</span><small>{file ? `${(file.size / 1_048_576).toFixed(1)} MB` : "Tap to browse from this device"}</small></label></div>{busy && progress > 0 ? <Progress value={progress} label="Uploading directly to private storage" /> : null}{error ? <div className="form-alert" role="alert">{error}</div> : null}{message ? <div className="form-success" role="status">{message}</div> : null}<div className="upload-actions"><Button type="button" onClick={upload} disabled={!file || busy}>{busy ? <LoaderCircle className="spin" size={18} /> : <UploadCloud size={18} />} Upload privately</Button><Button type="button" variant="secondary" onClick={createJob} disabled={!sourceAssetId || busy}><Box size={18} /> Create 3D job</Button></div></div>;
}
