"use client";

import { createElement, useEffect, useRef, useState } from "react";
import { Box, RotateCcw, ScanLine } from "lucide-react";
import { Button, Progress } from "@bsocio/ui";

export function SecureModelViewer({ modelId, productName }: { modelId: string; productName: string }) {
  const [active, setActive] = useState(false); const [url, setUrl] = useState(""); const [error, setError] = useState(""); const [progress, setProgress] = useState(0); const [autoRotate, setAutoRotate] = useState(true); const [presentation, setPresentation] = useState<{ scale: number; cameraOrbit?: string }>({ scale: 1 }); const viewer = useRef<HTMLElement | null>(null);
  useEffect(() => { if (!active || url) return; let cancelled = false; import("@google/model-viewer").then(async () => { const response = await fetch(`/api/models/${modelId}/signed-url`, { cache: "no-store" }); const payload = await response.json() as { data?: { url?: string; presentation?: { scale?: number; cameraOrbit?: string } }; error?: { message?: string } }; if (!cancelled) { if (!response.ok || !payload.data?.url) setError(payload.error?.message ?? "The private model could not be opened."); else { setUrl(payload.data.url); setPresentation({ scale: payload.data.presentation?.scale ?? 1, cameraOrbit: payload.data.presentation?.cameraOrbit }); } } }).catch(() => { if (!cancelled) setError("The 3D viewer could not be loaded on this device."); }); return () => { cancelled = true; }; }, [active, modelId, url]);
  useEffect(() => { const element = viewer.current; if (!element) return; const update = (event: Event) => { const detail = (event as CustomEvent<{ totalProgress?: number }>).detail; setProgress(Math.round((detail?.totalProgress ?? 0) * 100)); }; element.addEventListener("progress", update); return () => element.removeEventListener("progress", update); }, [url]);
  if (!active) return <div className="model-placeholder"><Box size={42} /><strong>Private 3D preview</strong><span>The GLB loads only when you open it, using a short-lived signed URL.</span><Button onClick={() => setActive(true)}>Open 3D model</Button></div>;
  if (error) return <div className="model-placeholder error"><Box size={42} /><strong>Preview unavailable</strong><span>{error}</span><Button variant="secondary" onClick={() => { setError(""); setActive(false); }}>Try again</Button></div>;
  if (!url) return <div className="model-placeholder"><span className="viewer-loader" /><strong>Authorizing private model…</strong></div>;
  const modelViewer = createElement("model-viewer", { ref: (node: HTMLElement | null) => { viewer.current = node; }, src: url, alt: `Interactive 3D model of ${productName}`, ar: true, "ar-modes": "webxr scene-viewer quick-look", "camera-controls": true, "touch-action": "pan-y", "auto-rotate": autoRotate || undefined, "shadow-intensity": "1", "environment-image": "neutral", loading: "eager", reveal: "auto", scale: `${presentation.scale} ${presentation.scale} ${presentation.scale}`, "camera-orbit": presentation.cameraOrbit || undefined }, createElement("button", { slot: "ar-button", className: "button button-primary viewer-ar-button" }, createElement(ScanLine, { size: 18 }), "View in your space"));
  return <div className="model-viewer-wrap"><div className="model-stage">{modelViewer}</div>{progress < 100 ? <Progress value={progress} label="Loading secure model" /> : null}<div className="viewer-controls"><Button variant="secondary" onClick={() => setAutoRotate((value) => !value)}>{autoRotate ? "Stop rotation" : "Auto rotate"}</Button><Button variant="ghost" onClick={() => viewer.current?.setAttribute("camera-orbit", presentation.cameraOrbit || "auto auto auto")}><RotateCcw size={17} /> Reset camera</Button></div></div>;
}
